// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4jg6SlMPmP9rEKoJ2ypkDmiBXhGm1uY',
    appId: '1:426691748366:web:f355ed3f7746d48701d25f',
    messagingSenderId: '426691748366',
    projectId: 'mentorme-d9fad',
    authDomain: 'mentorme-d9fad.firebaseapp.com',
    storageBucket: 'mentorme-d9fad.appspot.com',
    measurementId: 'G-3LHNG7GTFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGLFuioplYx2FD_yaYCElncVAfhSivC4',
    appId: '1:426691748366:android:2e6c7566bc7e5f3101d25f',
    messagingSenderId: '426691748366',
    projectId: 'mentorme-d9fad',
    storageBucket: 'mentorme-d9fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClKk3vOxuszh3JQtcuwDCuu5TZQGxEYvk',
    appId: '1:426691748366:ios:4ab02f9f97478b7101d25f',
    messagingSenderId: '426691748366',
    projectId: 'mentorme-d9fad',
    storageBucket: 'mentorme-d9fad.appspot.com',
    iosClientId: '426691748366-kmfb4otj18t2rovb85jl8rdvj229jdgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClKk3vOxuszh3JQtcuwDCuu5TZQGxEYvk',
    appId: '1:426691748366:ios:4ab02f9f97478b7101d25f',
    messagingSenderId: '426691748366',
    projectId: 'mentorme-d9fad',
    storageBucket: 'mentorme-d9fad.appspot.com',
    iosClientId: '426691748366-kmfb4otj18t2rovb85jl8rdvj229jdgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorme',
  );
}
